- name: Update apt cache
  apt:
    update_cache: yes
    force_apt_get: yes
  register: result
  until: result is succeeded
  delay: 10
  retries: 30
  become: true

- name: Add python apt repository
  apt_repository:
    validate_certs: no
    repo: "ppa:deadsnakes/ppa"
    state: present
  become: true

- name: Install Python
  apt:
    name:
      - "python{{python_version}}"
      - "python{{python_version}}-venv"
      - "python{{python_version}}-dev"
      - build-essential
  become: true

- name: Install pip, ignore possible error
  shell: "python{{python_version}} -m ensurepip"
  become: true
  ignore_errors: yes

- name: Install virtualenv
  pip:
    executable: "pip{{python_version}}"
    name: virtualenv
  become: true

- name: Copy requirements.txt
  copy:
    src: "{{ requirements }}"
    dest: /home/ubuntu/requirements.txt

- name: Install python dependencies
  pip:
    virtualenv_python: "python{{python_version}}"
    virtualenv: "{{ virtualenv }}"
    requirements: /home/ubuntu/requirements.txt
